/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/build-exam`; params?: Router.UnknownInputParams; } | { pathname: `/category-exams`; params?: Router.UnknownInputParams; } | { pathname: `/challenge-game`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/material-exams`; params?: Router.UnknownInputParams; } | { pathname: `/parent-home`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/solve-exam`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/challenge` | `/challenge`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chapters` | `/chapters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/common-mistakes` | `/common-mistakes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exams` | `/exams`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mistakes` | `/mistakes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/build-exam`; params?: Router.UnknownOutputParams; } | { pathname: `/category-exams`; params?: Router.UnknownOutputParams; } | { pathname: `/challenge-game`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/material-exams`; params?: Router.UnknownOutputParams; } | { pathname: `/parent-home`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/solve-exam`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/challenge` | `/challenge`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chapters` | `/chapters`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/common-mistakes` | `/common-mistakes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/exams` | `/exams`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mistakes` | `/mistakes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/build-exam${`?${string}` | `#${string}` | ''}` | `/category-exams${`?${string}` | `#${string}` | ''}` | `/challenge-game${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/material-exams${`?${string}` | `#${string}` | ''}` | `/parent-home${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/solve-exam${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/challenge${`?${string}` | `#${string}` | ''}` | `/challenge${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chapters${`?${string}` | `#${string}` | ''}` | `/chapters${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chats${`?${string}` | `#${string}` | ''}` | `/chats${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/common-mistakes${`?${string}` | `#${string}` | ''}` | `/common-mistakes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/exams${`?${string}` | `#${string}` | ''}` | `/exams${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mistakes${`?${string}` | `#${string}` | ''}` | `/mistakes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/build-exam`; params?: Router.UnknownInputParams; } | { pathname: `/category-exams`; params?: Router.UnknownInputParams; } | { pathname: `/challenge-game`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/material-exams`; params?: Router.UnknownInputParams; } | { pathname: `/parent-home`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/solve-exam`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/challenge` | `/challenge`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chapters` | `/chapters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/common-mistakes` | `/common-mistakes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exams` | `/exams`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mistakes` | `/mistakes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
